spring:
  application:
    name: mscartoes
  datasource:
    url: jdbc:mysql://192.168.1.10:3306/avaliadorcredito
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    open-in-view: false
  jackson:
    serialization:
      INDENT_OUTPUT: true
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: clovis.gargione
    password: tr0ub4do
  profiles:
    active: docker
server:
  port: 0
  servlet:
    context-path: /api/v1

eureka:
  client:
    fetch-registry: true
    registerWithEureka: true
    service-url:
      defaultZone: http://mseurekauser:ecok-usr-eeuramssur@eurekaserver:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
mq:
  queues:
    emissao-cartoes: emissao-cartoes
management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  file:
    name: ./logs/log-file.log
springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    defaultModelsExpandDepth: -1    
